"""
Block D / Week 14 — data-freeze memo TEMPLATE generator (support only).

WHAT THIS DOES
--------------
Writes a DRAFT data-freeze memo *template* with placeholders for the human to
fill in. It makes NO final claims and does NOT freeze anything: it does not tag
the repo, does not freeze MLflow runs, and does not decide the cohort. Where a
count is cheaply and unambiguously derivable from existing artefacts (e.g. the
quarantine decisions), it is offered as a clearly-labelled, non-authoritative
SUGGESTION in parentheses that the reviewer must verify before sign-off.

OUTPUT
------
reports/data_freeze_memo_TEMPLATE.md
"""

from __future__ import annotations

import json

from airway import config

OUT_MD = config.REPORTS_DIR / "data_freeze_memo_TEMPLATE.md"


def _suggestions() -> dict:
    """Best-effort, non-authoritative counts from existing artefacts."""
    s = {}
    try:
        import pandas as pd
        if config.LABELS_CSV.exists():
            s["n_labelled_patients"] = int(len(pd.read_csv(config.LABELS_CSV)))
    except Exception:  # noqa: BLE001
        pass
    try:
        import pandas as pd

        from airway import fusion
        if fusion.FUSION_FOLD_PRED_CSV.exists():
            preds = pd.read_csv(fusion.FUSION_FOLD_PRED_CSV)
            s["n_modelled_patients"] = int(preds[config.ID_COL].nunique())
    except Exception:  # noqa: BLE001
        pass
    try:
        q = config.PROCESSED_DIR / "quarantine_decisions.json"
        if q.exists():
            counts = json.loads(q.read_text()).get("counts", {})
            s["n_excluded_patients"] = counts.get("n_excluded_patients")
            s["n_excluded_images"] = counts.get("n_excluded_images")
    except Exception:  # noqa: BLE001
        pass
    return s


def _sg(s: dict, key: str) -> str:
    """Render a suggestion suffix if available."""
    return f"  _(auto-detected suggestion: {s[key]} — verify)_" if s.get(key) is not None else ""


def build_memo() -> str:
    s = _suggestions()
    return "\n".join([
        "# Data-Freeze Memo — DRAFT TEMPLATE",
        "",
        "> ⚠️ DRAFT TEMPLATE generated by `python -m airway.data_freeze`. It makes",
        "> no final claims and freezes nothing. Fill every `{{PLACEHOLDER}}`, verify",
        "> the auto-detected suggestions, and complete sign-off MANUALLY. The repo",
        "> tag and the MLflow run freeze are done by a human, not this script.",
        "",
        "## 1. Freeze identification",
        "",
        "- Freeze date: `{{FREEZE_DATE}}`",
        "- Dataset version / commit hash: `{{DATASET_VERSION_OR_HASH}}`",
        "- Data DVC hash: `{{DVC_DATA_HASH}}`",
        "- Prepared by: `{{PREPARER_NAME}}`",
        "",
        "## 2. Cohort counts (verify all)",
        "",
        f"- Number of patients (labelled): `{{{{N_PATIENTS}}}}`{_sg(s, 'n_labelled_patients')}",
        f"- Number modelled (face + ultrasound + label): `{{{{N_MODELLED}}}}`{_sg(s, 'n_modelled_patients')}",
        f"- Number of excluded patients: `{{{{N_EXCLUDED_PATIENTS}}}}`{_sg(s, 'n_excluded_patients')}",
        f"- Number of excluded images: `{{{{N_EXCLUDED_IMAGES}}}}`{_sg(s, 'n_excluded_images')}",
        "- Final INCLUDED patient count: `{{N_INCLUDED_FINAL}}`",
        "- Final EXCLUDED patient count: `{{N_EXCLUDED_FINAL}}`",
        "",
        "## 3. Change since Block B",
        "",
        "- Patients ADDED since Block B: `{{N_ADDED_SINCE_BLOCK_B}}` (ids: `{{IDS_ADDED}}`)",
        "- Patients REMOVED since Block B: `{{N_REMOVED_SINCE_BLOCK_B}}` (ids: `{{IDS_REMOVED}}`)",
        "- Reason(s) for change: `{{CHANGE_REASONS}}`",
        "",
        "## 4. MLflow runs (to be frozen MANUALLY)",
        "",
        "- Face model run id: `{{MLFLOW_RUN_ID_FACE}}`",
        "- Ultrasound model run id: `{{MLFLOW_RUN_ID_ULTRASOUND}}`",
        "- Fusion model run id: `{{MLFLOW_RUN_ID_FUSION}}`",
        "- Calibration run id: `{{MLFLOW_RUN_ID_CALIBRATION}}`",
        "",
        "## 5. Manual sign-off",
        "",
        "- Clinical reviewer: `{{CLINICAL_REVIEWER}}`  — date: `{{SIGNOFF_DATE_CLINICAL}}`",
        "- Data/ML reviewer: `{{ML_REVIEWER}}`  — date: `{{SIGNOFF_DATE_ML}}`",
        "- Final data-freeze decision (APPROVED / HOLD): `{{FREEZE_DECISION}}`",
        "- Notes: `{{SIGNOFF_NOTES}}`",
        "",
    ])


def main() -> None:
    config.ensure_dirs()
    OUT_MD.write_text(build_memo())
    print(f"data-freeze memo TEMPLATE -> {OUT_MD}")
    print("This is a TEMPLATE only: no tagging, no MLflow freeze, no final decision.")


if __name__ == "__main__":
    main()
